### ISSUE TITLE
Build with optimizations. (-Os at least?)

### ISSUE THREAD

**Issue by OscarL** [coolcoder613eb/Haiku-PyAPI#8]
Just noticed that currently the `Be.so` lib is almost 15.5 MB (stripped: almost 7 MB). After adding `-Os` to the `SubDirC++Flags`, it goes down to 4.7 MB (stripped: almost 2.3 MB).

I understand that `-Os` enables most of `-O2` (the ones that do not increase size at least), and default is `-O0` (which would explain the huge difference in size).

Might be worth benchmarking both `-Os` and `-O2` cases at least?

**Comment by Zardshard** [comment]
About nanobind... As I was looking around at its documentation, I found

> nanobind is highly related to pybind11 and inherits most of its conventions and syntax. The main difference is a change in philosophy: pybind11 must deal with _all of C++_ to bind legacy codebases, while nanobind targets a smaller C++ subset. ***The codebase has to adapt to the binding tool and not the other way around***, which allows nanobind to be simpler and faster
> \- https://nanobind.readthedocs.io/en/latest/why.html (bolded text mine)

It seems that this has a good chance of failing for Haiku then.
